<section class="ftco-section">
    <div class="container">
        <div class="col-md-12 mb-5 pb-3">
            <h3><?= $params['dish']['name'] ?></h3>
            <form action="/admin/update-dish/<?= $params['dish']['id'] ?>" method="POST">
                <div class="form-group row">
                    <label for="inputName" class="col-sm-2 col-form-label">Név</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="inputName" name="name" value="<?= $params['dish']['name'] ?>">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputSlug" class="col-sm-2 col-form-label">Keresőbarát név</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="inputSlug" name="slug" value="<?= $params['dish']['slug'] ?>">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="exampleFormControlTextarea1" class="col-sm-2 col-form-label">Leírás</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="description"><?= $params['dish']['description'] ?></textarea>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="inputPrice" class="col-sm-2 col-form-label">Ár</label>
                    <div class="col-sm-10">
                        <input type="number" class="form-control" id="inputPrice" name="price" value="<?= $params['dish']['price'] ?>">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="inputType" class="col-sm-2 col-form-label">Típus</label>
                    <div class="col-sm-10">
                        <select name="dishTypeId" id="inputType" class="form-control">
                        <?php foreach ($params['dishtypes'] as $dishtype): ?>
                                <option class="text-dark" value="<?= $dishtype['id'] ?>" <?= $params['dish']['dishTypeId'] == $dishtype['id'] ? 'selected' : '' ?>>
                                <?= $dishtype['name'] ?> </option>                                
                        <?php endforeach; ?>
                            <!-- <option value="1">
                                Levesek </option>
                            <option value="2" selected="">
                                Főételek </option>
                            <option value="3">
                                Desszertek </option>
                            <option value="4">
                                Italok </option> -->
                        </select>
                    </div>
                </div>

                <div class="form-group row pb-3">
                    <div class="col-sm-2">Aktív</div>
                    <div class="col-sm-10">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="gridCheck1" name="isActive" <?= $params['dish']['isActive'] ? 'checked' : '' ?>>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Elküldés</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>